server:
  port: 8080
spring:
  application:
    name: board
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/board}
    username: ${DATABASE_USERNAME:board}
    password: ${DATABASE_PASSWORD:board}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
logging:
  level:
    com.board: DEBUG

jwt:
  secret:  ${JWT_SECRET:local-dev-secret-key-must-be-at-least-32-bytes!!}
  access-token-expiration: 3600000